@startuml

class JflixControl

class StartMenu

StartMenu : + userLogin()
StartMenu : + userSignup()

class MainMenu
MainMenu : +searchMovie()
MainMenu : +SearchCategory()
MainMenu : +movieWatched()
MainMenu : +watchList()

class Userinfo
Userinfo : +userFileIo()


class User
User : -passWord
User : -userName
User : etc

class MovieDatabase
MovieDatabase : +movieFileIo()

class MovieChoices
MovieChoices : +playMovie()
MovieChoices : +safeMovie()
MovieChoices : +watchLater()
MovieChoices : +deleteMovieFromList()

class movie
movie : +name
movie : +year
movie : +rating
movie : etc

class movieScanner

class seriesScanner

class series

interface playable



MainMenu *-- MovieDatabase
MovieDatabase *-- MovieChoices
StartMenu *-- Userinfo
StartMenu --* Userinfo


@enduml